_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 103
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 103
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.1
            "6": 4.35.2
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
batch_size:
    value: 128
epoch:
    value: 10
learning_rate:
    value: "2e-4"
