user_name: seongmin # 실험자 이름
model:
  model_name: kykim/electra-kor-base
early_stopping:
  min_delta: 0.0
  mode: max
  monitor: val_pearson
  patience: 5
  verbose: False
train:
  batch_size: 32
  learning_rate: 5e-4
  max_epoch: 1
  dropout : 0.2
  LossF: torch.nn.MSELoss
  optim: torch.optim.AdamW
  ## LossF와 optim은 torch.nn과 torch.optim을 꼭 적어야 합니다
  shuffle: True
data:
  train_path: ./data/raw/train.csv
  dev_path: ./data/raw/dev.csv
  test_path: ./data/raw/dev.csv
  predict_path: ./data/raw/test.csv
  checkpoint_path: ./checkpoint/
  output_path: ./output/
  submission_path: ./data/raw/sample_submission.csv
  val_path: ./data/raw/dev.csv
# inference 설정
inference:
  model_file_name: 0924_0643_seongmin
  model_path:
    path_1: output_(0923_0746_seongmin)
    path_2: output_(0923_0849_seongmin)
  model_weight:
    weight_1: 0.8
    weight_2: 0.9
  postprocessing_list: [False, False, False]
  save_name: data # ensemble의 파일 저장명
wandb_log_folder: run-20240923_085002-wkvfq5sl
seed: 42