user_name: sujin # 실험자 이름
model:
    model_name: snunlp/KR-ELECTRA-discriminator # 모델명
patience: 5
train:
    batch_size: 32
    learning_rate: 5e-6
    max_epoch: 10
    LossF: torch.nn.MSELoss
    optim: torch.optim.AdamW
    ## LossF와 optim은 torch.nn과 torch.optim을 꼭 적어야 합니다
    shuffle: True
data:
    train_path: ./data/raw/train.csv
    dev_path: ./data/raw/dev.csv
    test_path: ./data/raw/dev.csv
    predict_path: ./data/raw/test.csv
    checkpoint_path: ./checkpoint/
    output_path: ./output/
    submission_path: ./data/sample_submission.csv
    val_path: ./data/dev.csv
seed: 42
