user_name: seongmin # 실험자 이름
model:
  model_name: klue/roberta-small
early_stopping:
  min_delta: 0.0
  mode: max
  monitor: val_pearson
  patience: 5
  verbose: False
train:
  batch_size: 10
  learning_rate: 1e-5
  max_epoch: 8
  LossF: torch.nn.MSELoss
  optim: torch.optim.AdamW
  ## LossF와 optim은 torch.nn과 torch.optim을 꼭 적어야 합니다
  shuffle: True
data:
  train_path: ./data/train.csv
  dev_path: ./data/train.csv
  test_path: ./data/train.csv
  predict_path: ./data/train.csv
  checkpoint_path: ./checkpoint/
  output_path: ./output/
  submission_path: ./data/sample_submission.csv
  val_path: ./data_dev.csv
seed: 42