_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 103
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 103
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.1
            "6": 4.35.2
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
CFG:
    value:
        data:
            checkpoint_path: ./checkpoint/
            dev_path: ./data/dev.csv
            output_path: ./output/
            predict_path: ./data/test.csv
            submission_path: ./data/sample_submission.csv
            test_path: ./data/dev.csv
            train_path: ./data/train.csv
            val_path: ./data/dev.csv
        early_stopping:
            min_delta: 0
            mode: max
            monitor: val_pearson
            patience: 5
            verbose: false
        model:
            model_name: kykim/electra-kor-base
        seed: 42
        train:
            LossF: torch.nn.MSELoss
            batch_size: 64
            learning_rate: "1e-4"
            max_epoch: 20
            optim: torch.optim.AdamW
            shuffle: true
        user_name: seongmin
batch_size:
    value: 64
epoch:
    value: 20
learning_rate:
    value: "1e-4"
